# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sinatra-torrent"
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["JP Hastings-Spital"]
  s.date = "2012-07-01"
  s.description = "An extension to Sinatra which will allow you to run a webseeded torrent tracker of files in the folder you specify."
  s.email = "jphastings@gmail.com"
  s.files = [
    "Rakefile",
    "Readme.md",
    "VERSION",
    "lib/sinatra/torrent.rb",
    "lib/sinatra/torrent/activerecord.rb",
    "lib/sinatra/torrent/hashing.rb",
    "lib/sinatra/torrent/helpers.rb",
    "sinatra-torrent.gemspec",
    "spec/spec_helper.rb",
    "spec/torrent_spec.rb"
  ]
  s.homepage = "http://github.com/jphastings/sinatra-torrent"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "A sinatra extension to run webseeded torrent tracker"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 1.1.2"])
      s.add_runtime_dependency(%q<bencode>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 1.1.2"])
      s.add_dependency(%q<bencode>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 1.1.2"])
    s.add_dependency(%q<bencode>, [">= 0"])
  end
end

